# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: v14.16.0
        cache: 'npm'
    # 安装依赖
    - run: npm install
    # 构建
    - run: npm run build
    # 上传到服务器
    
    - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@c711f2c3391cac2876bf4c833590077f02e4bcb8
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_PRIVATE_KEY }}
        # Remote host
        REMOTE_HOST: ${{ secrets.SERVER_HOST}}
        # Remote user
        REMOTE_USER: ${{ secrets.USER_NAME }}
        # Source directory
        SOURCE: public/ # optional, default is 
        # Target directory
        TARGET: /home/hfy/sites/blog # optional, default is /home/REMOTE_USER/
        # Arguments to pass to rsync
        ARGS: -avz --delete # optional, default is -rltgoDzvO
